language: julia
os:
- linux
julia:
- 1.1
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
  matrix:
  - PART=1/20
  - PART=2/20
  - PART=3/20
  - PART=4/20
  - PART=5/20
  - PART=6/20
  - PART=7/20
  - PART=8/20
  - PART=9/20
  - PART=10/20
  - PART=11/20
  - PART=12/20
  - PART=13/20
  - PART=14/20
  - PART=15/20
  - PART=16/20
  - PART=17/20
  - PART=18/20
  - PART=19/20
  - PART=20/20
sudo: required
jobs:
  include:
  - stage: regenerate build.jl
    script: julia build_tarballs.jl --only-buildjl
    if: tag IS present
before_script:
- julia -e 'import Pkg; Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
- julia -e 'import Pkg; Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl");
  Pkg.build()'
script:
- julia build_tarballs.jl --part=$PART
deploy:
  provider: releases
  api_key:
    secure: SMuwob3lFSGCDbVuV56bEvvZVpWcC/HROoEFUPhs9HzUKByXhu+o2MYkwNllUCTNAqdzluYi8YSrKv5vk67SQ+3F51uz08AdcNXq/FzWo/+r6/4zywMefRuM0v51xKLAe5jw2hs3P5Vv87lFQjsDrGvNAOC7Gs9pfw1EqS4PmiPx3iG6vpZrnAsaN43u/iTeSMddP2wcI+GWZXToJjVUpcvZ9gokYCGYKuV+x5PhPl/G3R07OscndJWJFVDZOEonQs4aExzY10m8rTTfNd9aSU0YNjwLy6vkU2jqJa8ZRvsFOEMFivxmuhpNnBtyvsdxumA3m2zln8/Mm4GpSwD1Ajkzhl1ASHVBAuUo9zJTtgCjz6xwoojFRj+Hh4G4bujxcppfPKZAHtANE1DueaNVglUbnIbE0R/WyHRkZ9zRJpWBMhyvOvsygJe7oVPAKUf6csh37MiasFWDdnC/d42HJht0Ay/WosV1Qnh+u90gZoSho8wCbXHQCH99b69vYm+Qgh0fVzwK2ErLg3uCH8WO1WGZAn9MDSdf47Tjn5wlWOgRXbfcXYcoY7ZMdgfNPMRoj8TZ8CiAFxPqL5Zy08VmPxF6Unv4IRrU/KvpniZ52PtUsKSie9pQGmpI/kQ8aE1QwSwTIzbYZioUnSlXjVS58YX4DDcKnKN+DdHFIEdPa9w=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: kdheepak/ZMQBuilder
    tags: true
